# Generated by Django 2.1.11 on 2019-10-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NPCGenerator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='FName',
        ),
    ]
