# Generated by Django 2.1.11 on 2019-10-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPCGenerator', '0004_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allign', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='race',
            old_name='Race',
            new_name='race',
        ),
    ]
