# Generated by Django 2.1.11 on 2019-10-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NPCGenerator', '0006_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='Gender',
            new_name='gender',
        ),
    ]
