# Generated by Django 2.1.11 on 2019-10-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NPCGenerator', '0008_classtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtype',
            old_name='ClassType',
            new_name='classtype',
        ),
    ]
