# Generated by Django 2.1.11 on 2019-10-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPCGenerator', '0010_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20)),
            ],
        ),
    ]
