# Generated by Django 2.1.11 on 2019-10-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPCGenerator', '0014_getall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhysTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phystrait', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SocTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soctrait', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='GetAll',
        ),
        migrations.RenameField(
            model_name='allign',
            old_name='allign',
            new_name='allignment',
        ),
    ]
