# Generated by Django 2.1.11 on 2019-10-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NPCGenerator', '0015_auto_20191010_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allign',
            new_name='Allignment',
        ),
    ]
