# Generated by Django 2.1.11 on 2019-10-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPCGenerator', '0016_auto_20191010_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtype',
            name='classtype',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lname',
            name='lname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='phystrait',
            name='phystrait',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='soctrait',
            name='soctrait',
            field=models.CharField(max_length=35),
        ),
    ]
